// c:\Users\Alperen\Desktop\flutter-yt\tobeto\lib\src\models.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'announcement_model.dart';
export 'application_model.dart';
export 'avatar_model.dart';
export 'blog_model.dart';
export 'calendar_model.dart';
export 'certificate_model.dart';
export 'contact_form_model.dart';
export 'course_model.dart';
export 'course_video_model.dart';
export 'education_model.dart';
export 'experience_model.dart';
export 'language_model.dart';
export 'skill_model.dart';
export 'social_media_model.dart';
export 'staff_model.dart';
export 'user_model.dart';