// c:\Users\Alperen\Desktop\flutter-yt\tobeto\lib\src\presentation\screens\platform.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'nav_bar_screens/nav_bar_screens.dart';
export 'profile_edit_screen_tabs/profile_edit_screen_tabs.dart';
export 'widgets/widgets.dart';
export 'platform_screen.dart';
export 'profile_edit_screen.dart';