// c:\Users\Alperen\Desktop\flutter-yt\tobeto\lib\src\presentation\screens\onboarding.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'onboarding_screen.dart';