// c:\Users\Alperen\Desktop\flutter-yt\tobeto\lib\src\presentation\screens\admin_course.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'admin_course_screen.dart';
export 'admin_course_video_screen.dart';