// c:\Users\Alperen\Desktop\flutter-yt\tobeto\lib\src\presentation\screens\platform\nav_bar_screens.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'applications_tab_screen.dart';
export 'course_tab_screen.dart';
export 'platform_tab_screen.dart';
export 'profile_details_tab_screen.dart';