// c:\Users\Alperen\Desktop\flutter-yt\tobeto\lib\src\presentation\screens\for_companies\widgets.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'for_companies_card.dart';
export 'for_companies_card_content.dart';