// c:\Users\Alperen\Desktop\flutter-yt\tobeto\lib\src\presentation\screens\platform\profile_edit_screen_tabs.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'edit_certificate_tab.dart';
export 'edit_education_tab.dart';
export 'edit_experience_tab.dart';
export 'edit_languages_tab.dart';
export 'edit_personel_info_tab.dart';
export 'edit_settings_tab.dart';
export 'edit_skills_tab.dart';
export 'edit_social_media_tab.dart';