// c:\Users\Alperen\Desktop\flutter-yt\tobeto\lib\src\presentation\screens\in_the_press.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'in_the_press_screen.dart';