// c:\Users\Alperen\Desktop\flutter-yt\tobeto\lib\src\presentation\screens\contact_us\widgets.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'communication_info.dart';