// c:\Users\Alperen\Desktop\flutter-yt\tobeto\lib\src\presentation\screens\for_individuals\widgets.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'for_individuals_image_card.dart';
export 'for_individuals_page_text.dart';
export 'for_individuals_sector_card.dart';