// c:\Users\Alperen\Desktop\flutter-yt\tobeto\lib\src\presentation\screens\admin_applications.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'admin_applications_screen.dart';